author: Zarius (Updated by CoolLord22)
database: false
description: Plugin that allows world-terrain recipes.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.gmail.zariust.mcplugins.othergrowth.OtherGrowth
name: OtherGrowth
startup: postworld
url: http://www.website.here/
version: '1.0'
commands:
    og:
        description: Administrate the OtherGrowth plugin
        aliases: [ogr]
        usage: |
            OtherGrowth 1.0

            (/ogr) /og reload - reload config

