author: Zarius
database: false
description: Description goes here.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.gmail.zariust.mcplugins.othergrowth.OtherGrowth
name: OtherGrowth
startup: postworld
url: http://www.website.here/
version: '0.2'
commands:
    og:
        description: Administrate the OtherGrowth plugin
        aliases: [ogr]
        usage: |
            OtherGrowth 

            (/ogr) /og reload - reload config

